/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Health check endpoint.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Verify
         * @description Content verification endpoint.
         *
         *     Accepts either:
         *       - input_type="url" + image_url (URL to an image)
         *       - input_type="file" + file (multipart upload)
         *
         *     Returns a VerifyResponse with classification results.
         *     This is a schema-only stub for M0; actual pipeline wired in M7.
         */
        post: operations["verify_verify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_verify_verify_post */
        Body_verify_verify_post: {
            input_type: components["schemas"]["InputType"];
            /** Image Url */
            image_url?: string | null;
            /** File */
            file?: string | null;
        };
        /**
         * EvidenceStrength
         * @enum {string}
         */
        EvidenceStrength: "Strong" | "Moderate" | "Limited";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * InputType
         * @enum {string}
         */
        InputType: "url" | "file";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * VerifyResponse
         * @description POST /verify response payload.
         *
         *     Returned after the verification pipeline completes (or fails).
         *     The `id` field is the UUID of the saved receipts row, used to
         *     construct the receipt image URL: /api/receipt/{id}
         */
        VerifyResponse: {
            /**
             * Id
             * @description UUID of the saved receipts row
             */
            id: string;
            /**
             * Classification
             * @description One of: "AI-Generated Content", "Verified Camera Original", "Recirculated / Out of Context", "Post-Processed Image", "Unverified — No Provenance Found"
             */
            classification: string;
            evidence_strength: components["schemas"]["EvidenceStrength"];
            /**
             * Evidence
             * @description Itemized list of all matched evidence findings
             */
            evidence: string[];
            /**
             * Interpretation
             * @description Plain-language sentence contextualizing the classification
             */
            interpretation: string;
            /** Processing Time Ms */
            processing_time_ms: number;
            /**
             * Receipt Image Url
             * @description URL to the server-generated receipt image: /api/receipt/{id}
             */
            receipt_image_url: string;
            /**
             * Cached
             * @description True if this result was served from the SHA-256 cache
             * @default false
             */
            cached: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    verify_verify_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_verify_verify_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VerifyResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
